# Generated by Django 3.0.2 on 2020-02-04 12:14

from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(upload_to=images.models.storage_path)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[(0, 'Image in unknown status'), (1, 'Image is uploaded to S3 but staged'), (2, 'Image is uploaded and associated with another resource')], default=0, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
